In [3]:
# Description: This program classifies a person as having a cardiovasculer disease or not.


## Import some important libraries
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
# Load the data
df = pd.read_csv(r'cardio_train.csv', sep = ';')

In [5]:
df.head()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [6]:
# get the shape of data
df.shape

(70000, 13)

In [7]:
# Count the empty or nan value in the dataset
df.isna().sum()

id             0
age            0
gender         0
height         0
weight         0
ap_hi          0
ap_lo          0
cholesterol    0
gluc           0
smoke          0
alco           0
active         0
cardio         0
dtype: int64

In [8]:
# Another way to check for any missing value
df.isnull().values.any()

np.False_

In [9]:
# view some basic statistics
df.describe()

,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
count,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000,70000.000000
mean,49972.419900,19468.865814,1.349571,164.359229,74.205690,128.817286,96.630414,1.366871,1.226457,0.088129,0.053771,0.803729,0.499700
std,28851.302323,2467.251667,0.476838,8.210126,14.395757,154.011419,188.472530,0.680250,0.572270,0.283484,0.225568,0.397179,0.500003
min,0.000000,10798.000000,1.000000,55.000000,10.000000,-150.000000,-70.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,25006.750000,17664.000000,1.000000,159.000000,65.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
50%,50001.500000,19703.000000,1.000000,165.000000,72.000000,120.000000,80.000000,1.000000,1.000000,0.000000,0.000000,1.000000,0.000000
75%,74889.250000,21327.000000,2.000000,170.000000,82.000000,140.000000,90.000000,2.000000,1.000000,0.000000,0.000000,1.000000,1.000000
max,99999.000000,23713.000000,2.000000,250.000000,200.000000,16020.000000,11000.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000

In [10]:
# Get a count of the number of patients with a cardivascular disease and without
df['cardio'].value_counts()

cardio
0    35021
1    34979
Name: count, dtype: int64

In [ ]:
# visualise the counts
sns.countplot(df['cardio'])

Error in callback <function flush_figures at 0x0000020C4AD62400> (for post_execute), with arguments args (),kwargs {}:

In [ ]:
# Look at the number of people with a cardiovescular disease that exceed the number of the people without a cardiovescular disease

# create a years column
df['years'] = (df['age']/365).round(0) 
df['years'] = pd.to_numeric(df['years'], downcast = 'integer')

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(17, 17))
sns.countplot(
    x='years',
    hue='cardio',
    data=df,
    palette='colorblind',
    edgecolor=sns.color_palette('dark', n_colors=1)[0]  # Extract the single color
)
plt.title('Count of Cardio Cases by Age (Years)')
plt.xlabel('Years')
plt.ylabel('Count')
plt.show()

In [ ]:
# get the correlation of the column
df.corr()

In [ ]:
# visualise the data

plt.figure(figsize =( 17,17))
sns.heatmap(df.corr(), annot = True, fmt = '.0%')

In [ ]:
# lets remove or drop the yeras column
df = df.drop('years', axis = 1 )

In [ ]:
# lets remove or drop the id column
df = df.drop('id', axis = 1 )

In [ ]:
# split the data into feature data and target data
x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

In [ ]:
# split the data set into 75% training dataset and 25% testing dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 1)

In [ ]:
# Feature Scalling
# scale the values in the data to be values between 0 and 1 inclusive
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(x_train)
X_test = sc.fit_transform(x_test)

In [ ]:
# Use RandomForestClassifier
from sklearn.ensemble import RandomForestClassifier
forest = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 1)
forest.fit(X_train, y_train)

In [ ]:
# Test the model accuracy on the training dataset
model = forest
model.score(X_train, y_train)

In [ ]:
# Test the models accuracy on the test dataset
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, model.predict(X_test))
TN = cm[0][0]
TP = cm[1][1]
FN = cm[1][0]
FP = cm[0][1]
# Print the confusion matrix
print(cm)

# Print the model accuracy on the test data
print('Model Test Accuracy = {}'.format((TP+TN)/(TP+TN+FN+FP)))